import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Providers from "./providers";
// import ThemeProvider from "../app/ThemeProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Handle Products",
  description: "Generated by Mohanad Hassan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider> */}
          <Providers><Navbar/>{children}</Providers>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}